Repository ProjetaoMUS/pedaloo-front, pull requests merged in 2023-10, with the labels that each got.

#25 HOTFIX: Disable automatic login
  App.tsx
Labels: bug

#27 Feature/new style parking places
  src/api/auth.tsx
  src/api/partnerLocation.tsx
  src/api/user-data.tsx
  src/screens/ParkingPlacesList/index.tsx
Labels: enhancement

#29 Feature/make reservations
  App.tsx
  src/api/auth.tsx
  src/api/partnerLocation.tsx
  src/api/reservation.tsx
  src/screens/LoginForm/index.tsx
  src/screens/ParkingPlaceInfo/index.tsx
  src/screens/Profile/index.tsx
  src/screens/ReservationScreen/index.tsx
  src/types/reservation.tsx
Labels: enhancement, review

#28 Feature/my reservations screen
  assets/qr_code.png
  src/api/auth.tsx
  src/api/reservationLocation.tsx
  src/screens/BookingDetails/index.tsx
  src/screens/LoginOptions/index.tsx
  src/screens/MyReservations/index.tsx
  src/screens/Navbar/index.tsx
Labels: review

#23 Refactor navigation system
  App.tsx
  src/screens/BookingDetails/index.tsx
  src/screens/Home/index.tsx
  src/screens/Home/styles.ts
  src/screens/Login/index.tsx
  src/screens/LoginForm/index.tsx
  src/screens/LoginForm/password-input.tsx
  src/screens/LoginOptions/index.tsx
  src/screens/LoginOptions/option-button.tsx
  src/screens/Maps/index.tsx
  src/screens/MyReservations/index.tsx
  src/screens/Navbar/index.tsx
  src/screens/Navbar/profile-header.tsx
  src/screens/ParkingPlaceInfo/carousel-image.tsx
  src/screens/ParkingPlaceInfo/index.tsx
  src/screens/ParkingPlaceInfo/stars.tsx
  src/screens/ParkingPlaces/index.tsx
  src/screens/Profile/index.tsx
  src/screens/Profile/menu-button.tsx
  src/screens/ReservationScreen/index.tsx
  src/screens/Search/index.tsx
Labels: enhancement, wip
