Repository ProjetaoMUS/pedaloo-front, pull requests merged in 2023-09, with the labels that each got.

#9 Change color of login screen
  assets/green-logo.png
  src/screens/Login/index.tsx
Labels: review

#10 Show reservation screen from booking screen
  src/screens/ParkingPlaces/index.tsx
Labels: enhancement, review

#8 Feature/functional search places to park
  src/api/partnerLocation.tsx
  src/screens/ParkingPlaces/index.tsx
Labels: enhancement

#11 Added useEffect
  src/screens/ParkingPlaces/index.tsx
Labels: bug

#15 Refactor login page flow and style
  App.tsx
  package-lock.json
  package.json
  src/screens/Login/index.tsx
  src/screens/LoginForm/index.tsx
  src/screens/LoginOptions/index.tsx
  src/screens/Navbar/index.tsx
  src/screens/ParkingPlaces/index.tsx
Labels: enhancement, review

#14 Embelish parking places screen
  src/screens/ParkingPlaces/index.tsx
  src/screens/ParkingPlaces/styles.ts
Labels: enhancement, review

#16 Refactor reservation page flow and style
  src/screens/ParkingPlaces/index.tsx
  src/screens/ParkingPlacesList/index.tsx
  src/screens/ReservationScreen/index.tsx
Labels: enhancement, review

#17 Migrate deprecated tab bar options
  src/screens/Navbar/index.tsx
Labels: review

#18 Add new feature: feedback messages
  App.tsx
  src/contexts/feedback.tsx
  src/screens/Feedback/index.tsx
  src/screens/LoginForm/index.tsx
Labels: enhancement, review

#20 Implement profile page and related subpages
  assets/avatar.png
  assets/camera-icon.png
  package-lock.json
  package.json
  src/api/user-data.tsx
  src/contexts/profile.tsx
  src/screens/Account/index.tsx
  src/screens/Help/index.tsx
  src/screens/Navbar/index.tsx
  src/screens/Profile/index.tsx
  src/screens/Settings/index.tsx
Labels: enhancement, review

#19 Update style in login page
  src/screens/LoginForm/index.tsx
  src/screens/LoginOptions/index.tsx
Labels: enhancement, review
